@echo off
echo Starting PostgreSQL server...
echo This window will keep the server running...
start "PostgreSQL Server" /wait psql-setup.exe first_run

echo.
echo Starting database creation in a new window...
start "PostgreSQL Database Setup" cmd /c "psql-setup.exe second_run && pause"