name: Build FastAPI 

on:[push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Pulling the code
        uses: actions/checkout@v2
      - name: Say Hi Subin
        run: echo "Hi Subin"