name: Python API Development

on:
  push:
    paths:
      - 'Python API Development - Comprehensive Course for Beginners/**'
  pull_request:
    paths:
      - 'Python API Development - Comprehensive Course for Beginners/**'

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          sparse-checkout: true
          sparse-checkout-pattern: 'Python API Development - Comprehensive Course for Beginners'
      - name: Say Hi Subin
        run: echo "Hi Subin"