name: Python API Development

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          sparse-checkout: true
          sparse-checkout-pattern: 'Python API Development - Comprehensive Course for Beginners'
      - name: Say Hi Subin
        run: echo "Hi Subin"
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r "Python API Development - Comprehensive Course for Beginners/requirements.txt"
      - name: Run tests
        run: |
          cd "Python API Development - Comprehensive Course for Beginners"
          pip install pytest
          pytest --version
          pytest